name: aarch64_runtime
on:
  workflow_dispatch:

jobs:
  rscc_tests:
    runs-on: ubuntu-latest
    name: Test on ubuntu-22.04 aarch64
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "yuchanns/rscc"
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}:/workspace"
          run: |
            # Install gcc, g++, libc6-dev and curl
            apt-get update && apt-get install -y gcc g++ libc6-dev curl
            # Install rust
            export CARGO_HOME=$HOME/.cargo
            export RUSTUP_HOME=$HOME/.rustup
            curl -fsSL https://sh.rustup.rs | sh -s -- -y --default-toolchain=stable --profile=minimal
            source $CARGO_HOME/env
            cargo version
            # Run tests
            cd /workspace
            cargo test
