name: m1_runtime
on:
  workflow_dispatch:

jobs:
  rscc_tests:
    runs-on: macos-latest
    name: Test on macOS arm64
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "yuchanns/rscc"
      - name: Run commands
        run: |
          sed -i '' 's/"-static", //g' tests/test.rs
          sed -i '' 's/main/_main/g' src/codegen.rs
          cargo test
